export enum PostApprovalAction {
  SUBMITTED_TO_CLIENT = 'SUBMITTED_TO_CLIENT',
  APPROVED = 'APPROVED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  REJECTED = 'REJECTED',
  PUBLISHED = 'PUBLISHED',
}