export enum LeadSource {
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  WHATSAPP = 'WHATSAPP',
  WEBSITE = 'WEBSITE',
  MANUAL = 'MANUAL',
  REFERRAL = 'REFERRAL',
  TIKTOK = 'TIKTOK',
  LINKEDIN = 'LINKEDIN',
  OTHER = 'OTHER',
}