export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  INTERESTED = 'INTERESTED',
  WAITING_DECISION = 'WAITING_DECISION',
  WON = 'WON',
  LOST = 'LOST',
  FOLLOW_UP_LATER = 'FOLLOW_UP_LATER',
}