export enum ContentPostStatus {
  DRAFT = 'DRAFT',
  IN_INTERNAL_REVIEW = 'IN_INTERNAL_REVIEW',
  READY_FOR_CLIENT = 'READY_FOR_CLIENT',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  PUBLISHED = 'PUBLISHED',
  CANCELED = 'CANCELED',
}