export enum NotificationType {
    TASK_ASSIGNED = 'TASK_ASSIGNED',
    TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
    TASK_COMMENTED = 'TASK_COMMENTED',

    POST_SUBMITTED_TO_CLIENT = 'POST_SUBMITTED_TO_CLIENT',
    POST_CHANGES_REQUESTED = 'POST_CHANGES_REQUESTED',
    POST_APPROVED = 'POST_APPROVED',
    POST_PUBLISHED = 'POST_PUBLISHED',
    POST_COMMENTED = 'POST_COMMENTED',
    POST_REJECTED = 'POST_REJECTED',

    LEAD_ASSIGNED = 'LEAD_ASSIGNED',
    LEAD_STATUS_CHANGED = 'LEAD_STATUS_CHANGED',
LEAD_NOTE_ADDED = 'LEAD_NOTE_ADDED',
    INVITATION_CREATED = 'INVITATION_CREATED',
    INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',

    REPORT_CREATED = 'REPORT_CREATED',
}