export enum CompanyMembershipRole {
  ACCOUNT_MANAGER = 'ACCOUNT_MANAGER',
  COPYWRITER = 'COPYWRITER',
  DESIGNER = 'DESIGNER',
  SOCIAL_MEDIA_MANAGER = 'SOCIAL_MEDIA_MANAGER',
  CLIENT_OWNER = 'CLIENT_OWNER',
  CLIENT_REVIEWER = 'CLIENT_REVIEWER',
  SALES_AGENT = 'SALES_AGENT',
}