export enum TaskType {
  COPYWRITING = 'COPYWRITING',
  DESIGN = 'DESIGN',
  CLIENT_REVIEW = 'CLIENT_REVIEW',
  FOLLOW_UP = 'FOLLOW_UP',
  PUBLISHING = 'PUBLISHING',
  REPORTING = 'REPORTING',
  GENERAL = 'GENERAL',
}