export enum ResponsibilityType {
  TO_MANAGE = 'TO_MANAGE',
  TO_SUPPORT = 'TO_SUPPORT',
  TO_FOLLOW_UP = 'TO_FOLLOW_UP',
  TO_BE_HELD_RESPONSIBLE = 'TO_BE_HELD_RESPONSIBLE',
  TO_APPROVE = 'TO_APPROVE',
  TO_WORK_ON = 'TO_WORK_ON',
  TO_CONSULT = 'TO_CONSULT',
  TO_COORDINATE = 'TO_COORDINATE',
  TO_BE_INFORMED = 'TO_BE_INFORMED',
  TO_SUPERVISE = 'TO_SUPERVISE',
  OTHER = 'OTHER',
}